### ISSUE TITLE
Unable to embed simple Dapp using library

### ISSUE THREAD

**Issue by schnogz** [LedgerHQ/ledger-live-wagmi-connector#3]
I am trying to connect a very simple CRA to Ledger Live.  When using this library, I am getting the following error message when trying to connect via
```
mutation.ts:243 Error: Response from provider did not have error or result key  at IFrameEthereumProvider._this2.handleEventSourceMessage (index.ts:327)
```

Ledger Live Manifest file --> https://github.com/schnogz/wagmi-ledger-live/blob/main/ledger-manifest.json
Wagmi config --> https://github.com/schnogz/wagmi-ledger-live/blob/main/src/App.js

You can find the source code [here](https://github.com/schnogz/wagmi-ledger-live). 

I tried to find other examples of people using this wagmi connector but was unable to do so.  Any help would be greatly appreciated!

**Comment by imqdee** [comment]
Hi @schnogz

First of all, thanks for your message.
I'm not sure it's clear regarding the readme of this repository, but the connector developed here is expected to be used to develop a Live App. What we call a live app, is a dApp that runs inside the discover section in the Ledger Live wallet. That means the dApp is embedded inside an iFrame and can be accessed from the discover section. 
Unfortunately, this connector doesn't manage the direct communication with the Ledger Live wallet, the dApp (called Live app in this context) needs to be embedded inside the discover section of Ledger Live to work.
By following the minimalist example in the readme, you can develop both a dApp and a Live app without compromise and a complex setup.

Was it clear to you? Do you try to enable a direct connection between your dApp and Ledger Live?

**Comment by chabroA** [comment]
Hi @schnogz 

Thanks for your message and your interest in building on top of the Ledger Platform 🙌 

I had a quick look at your code and have some feedbacks that might help you make your dapp work:

As explained by @qd-qd, your Dapp will run inside the [eth-dapp-browser](https://github.com/LedgerHQ/eth-dapp-browser). This is why you have 2 urls in the manifest, the first one, `url`, should be the url of the eth-dapp-browser. The second one, `dappUrl` inside the `params` object, should be the url of your dapp.
[Here](https://developers.ledger.com/docs/dapp/process/) is the documentation regarding developing a dapp on top of ledger (you don't have to worry about the DApp Plugin part for your POC) with the doc related to the manifest [here](https://developers.ledger.com/docs/dapp/manifest/). If anything in this doc is not clear or could be improved, don't hesitate to drop a comment / feedback in the appropriate comment box present at the end of each page so they can be improved 👍 

It looks like that you are using the same url (the url of your dapp I would assume) for both of these applications, which might cause your issue.

```json
  "url": "http://localhost:3001/?embed=true",
  "params": {
    "dappUrl": "http://localhost:3001/?embed=true",
```

Regarding your wagmi config, it looks fine overall but you could specify the `connector` as parameter of the `createClient` function in order to avoid specifying it for each hook call afterward.

For a quick example of a Dapp implementation using this wagmi connector, you can take a look at [this workshop repo](https://github.com/LedgerHQ/workshop-connect-dapp-ll/tree/solution) (under the `solution` branch).

**Comment by schnogz** [comment]
Thanks for the quick response @chabroA @qd-qd .

Yes I am building a Live App that will go into the Discover section of Ledger and this was just a small proof of concept.

The issue was as @chabroA pointed out, I was not running the ETH App Browser provided by ledger and my urls in the manifest were incorrect. Once I fixed that, it instantly connected!

I guess one piece of feedback would be to make it more obvious to a developer that they need to be running the ETH DApp Browser locally.  The description in the docs for `url` just says `https://dapp-browser.apps.ledger.com` and I guess I didn't realize that meant you needed to run ETH DAPP Browser alongside the actual DAPP the developer is building.  Perhaps the description for the `url` field could be updated to be something like `The url of the ETH App Browser either running locally or at https://dapp-browser.apps.ledger.com`.

**Comment by imqdee** [comment]
Your feedback is valuable, thanks! We’ll definitely update the documentation to make this part clearer. 

I’m glad we helped, don’t hesitate if you have any additional questions.
